CREATE TABLE IF NOT EXISTS production_log (
  id serial PRIMARY KEY,
  log_date date NOT NULL,
  log_from text,
  log_to text,
  is_daily_log boolean DEFAULT false,
  partner_id integer REFERENCES partner(id),
  operator_id integer REFERENCES staff(id),
  machine_id integer REFERENCES work_center(id),
  item_id integer REFERENCES item(id),
  utility_ratio numeric(5,2) DEFAULT 1.0,
  rm_item_id integer REFERENCES item(id),
  fixture text,
  good_pcs numeric(18,3) DEFAULT 0,
  good_kg numeric(18,3) DEFAULT 0,
  reject_pcs numeric(18,3) DEFAULT 0,
  reject_kg numeric(18,3) DEFAULT 0,
  rm_qty_kg numeric(18,3) DEFAULT 0,
  idle_reason text,
  rejection_reason text,
  remarks text,
  created_by integer REFERENCES staff(id),
  created_at timestamptz DEFAULT now()
);
