/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CutoverRouteImport } from './routes/cutover'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as FoundryRouteImport } from './routes/foundry'
import { Route as GrnRouteImport } from './routes/grn'
import { Route as GstRouteImport } from './routes/gst'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ImportRouteImport } from './routes/import'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as JwRouteImport } from './routes/jw'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as MovesRouteImport } from './routes/moves'
import { Route as NcrRouteImport } from './routes/ncr'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PoRouteImport } from './routes/po'
import { Route as ProdLogRouteImport } from './routes/prod-log'
import { Route as QcRouteImport } from './routes/qc'
import { Route as QrLabelsRouteImport } from './routes/qr-labels'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RegistersRouteImport } from './routes/registers'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SoRouteImport } from './routes/so'
import { Route as StnRouteImport } from './routes/stn'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SubcontractRouteImport } from './routes/subcontract'
import { Route as WoRouteImport } from './routes/wo'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as DevDocsRouteImport } from './routes/dev.docs'
import { Route as DevJourneysRouteImport } from './routes/dev.journeys'
import { Route as GenealogyLotIdRouteImport } from './routes/genealogy.$lotId'
import { Route as PrintCutoverPackRouteImport } from './routes/print.cutover-pack'
import { Route as SettingsGstRouteImport } from './routes/settings.gst'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DevDocsIndexRouteImport } from './routes/dev.docs.index'
import { Route as DevDocsSlugRouteImport } from './routes/dev.docs.$slug'
import { Route as PrintChallanIdRouteImport } from './routes/print.challan.$id'
import { Route as PrintCnIdRouteImport } from './routes/print.cn.$id'
import { Route as PrintCocIdRouteImport } from './routes/print.coc.$id'
import { Route as PrintDcIdRouteImport } from './routes/print.dc.$id'
import { Route as PrintDnIdRouteImport } from './routes/print.dn.$id'
import { Route as PrintEwayIdRouteImport } from './routes/print.eway.$id'
import { Route as PrintGrnIdRouteImport } from './routes/print.grn.$id'
import { Route as PrintInvoiceIdRouteImport } from './routes/print.invoice.$id'
import { Route as PrintKnockoutIdRouteImport } from './routes/print.knockout.$id'
import { Route as PrintOpeningJwIdRouteImport } from './routes/print.opening-jw.$id'
import { Route as PrintPackingIdRouteImport } from './routes/print.packing.$id'
import { Route as PrintPoIdRouteImport } from './routes/print.po.$id'
import { Route as PrintPourIdRouteImport } from './routes/print.pour.$id'
import { Route as PrintQrLotIdRouteImport } from './routes/print.qr.$lotId'
import { Route as PrintQuoteIdRouteImport } from './routes/print.quote.$id'
import { Route as PrintReturnIdRouteImport } from './routes/print.return.$id'
import { Route as PrintShippingBillIdRouteImport } from './routes/print.shipping-bill.$id'
import { Route as StockLotsLotIdGenealogyRouteImport } from './routes/stock.lots.$lotId.genealogy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CutoverRoute = CutoverRouteImport.update({
  id: '/cutover',
  path: '/cutover',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundryRoute = FoundryRouteImport.update({
  id: '/foundry',
  path: '/foundry',
  getParentRoute: () => rootRouteImport,
} as any)
const GrnRoute = GrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRoute = GstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const JwRoute = JwRouteImport.update({
  id: '/jw',
  path: '/jw',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const MovesRoute = MovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => rootRouteImport,
} as any)
const NcrRoute = NcrRouteImport.update({
  id: '/ncr',
  path: '/ncr',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PoRoute = PoRouteImport.update({
  id: '/po',
  path: '/po',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdLogRoute = ProdLogRouteImport.update({
  id: '/prod-log',
  path: '/prod-log',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const QrLabelsRoute = QrLabelsRouteImport.update({
  id: '/qr-labels',
  path: '/qr-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersRoute = RegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SoRoute = SoRouteImport.update({
  id: '/so',
  path: '/so',
  getParentRoute: () => rootRouteImport,
} as any)
const StnRoute = StnRouteImport.update({
  id: '/stn',
  path: '/stn',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractRoute = SubcontractRouteImport.update({
  id: '/subcontract',
  path: '/subcontract',
  getParentRoute: () => rootRouteImport,
} as any)
const WoRoute = WoRouteImport.update({
  id: '/wo',
  path: '/wo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDocsRoute = DevDocsRouteImport.update({
  id: '/dev/docs',
  path: '/dev/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevJourneysRoute = DevJourneysRouteImport.update({
  id: '/dev/journeys',
  path: '/dev/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const GenealogyLotIdRoute = GenealogyLotIdRouteImport.update({
  id: '/genealogy/$lotId',
  path: '/genealogy/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCutoverPackRoute = PrintCutoverPackRouteImport.update({
  id: '/print/cutover-pack',
  path: '/print/cutover-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGstRoute = SettingsGstRouteImport.update({
  id: '/settings/gst',
  path: '/settings/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDocsIndexRoute = DevDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevDocsRoute,
} as any)
const DevDocsSlugRoute = DevDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DevDocsRoute,
} as any)
const PrintChallanIdRoute = PrintChallanIdRouteImport.update({
  id: '/print/challan/$id',
  path: '/print/challan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCnIdRoute = PrintCnIdRouteImport.update({
  id: '/print/cn/$id',
  path: '/print/cn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCocIdRoute = PrintCocIdRouteImport.update({
  id: '/print/coc/$id',
  path: '/print/coc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintDcIdRoute = PrintDcIdRouteImport.update({
  id: '/print/dc/$id',
  path: '/print/dc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintDnIdRoute = PrintDnIdRouteImport.update({
  id: '/print/dn/$id',
  path: '/print/dn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintEwayIdRoute = PrintEwayIdRouteImport.update({
  id: '/print/eway/$id',
  path: '/print/eway/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintGrnIdRoute = PrintGrnIdRouteImport.update({
  id: '/print/grn/$id',
  path: '/print/grn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/invoice/$id',
  path: '/print/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintKnockoutIdRoute = PrintKnockoutIdRouteImport.update({
  id: '/print/knockout/$id',
  path: '/print/knockout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOpeningJwIdRoute = PrintOpeningJwIdRouteImport.update({
  id: '/print/opening-jw/$id',
  path: '/print/opening-jw/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPackingIdRoute = PrintPackingIdRouteImport.update({
  id: '/print/packing/$id',
  path: '/print/packing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPoIdRoute = PrintPoIdRouteImport.update({
  id: '/print/po/$id',
  path: '/print/po/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPourIdRoute = PrintPourIdRouteImport.update({
  id: '/print/pour/$id',
  path: '/print/pour/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintQrLotIdRoute = PrintQrLotIdRouteImport.update({
  id: '/print/qr/$lotId',
  path: '/print/qr/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintQuoteIdRoute = PrintQuoteIdRouteImport.update({
  id: '/print/quote/$id',
  path: '/print/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintReturnIdRoute = PrintReturnIdRouteImport.update({
  id: '/print/return/$id',
  path: '/print/return/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintShippingBillIdRoute = PrintShippingBillIdRouteImport.update({
  id: '/print/shipping-bill/$id',
  path: '/print/shipping-bill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StockLotsLotIdGenealogyRoute = StockLotsLotIdGenealogyRouteImport.update({
  id: '/lots/$lotId/genealogy',
  path: '/lots/$lotId/genealogy',
  getParentRoute: () => StockRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bills': typeof BillsRoute
  '/books': typeof BooksRoute
  '/cutover': typeof CutoverRoute
  '/dispatch': typeof DispatchRoute
  '/foundry': typeof FoundryRoute
  '/grn': typeof GrnRoute
  '/gst': typeof GstRoute
  '/healthz': typeof HealthzRoute
  '/import': typeof ImportRoute
  '/journeys': typeof JourneysRoute
  '/jw': typeof JwRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/masters': typeof MastersRoute
  '/moves': typeof MovesRoute
  '/ncr': typeof NcrRoute
  '/planning': typeof PlanningRoute
  '/po': typeof PoRoute
  '/prod-log': typeof ProdLogRoute
  '/qc': typeof QcRoute
  '/qr-labels': typeof QrLabelsRoute
  '/quotes': typeof QuotesRoute
  '/registers': typeof RegistersRoute
  '/shop': typeof ShopRoute
  '/so': typeof SoRoute
  '/stn': typeof StnRoute
  '/stock': typeof StockRouteWithChildren
  '/subcontract': typeof SubcontractRoute
  '/wo': typeof WoRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/dev/docs': typeof DevDocsRouteWithChildren
  '/dev/journeys': typeof DevJourneysRoute
  '/genealogy/$lotId': typeof GenealogyLotIdRoute
  '/print/cutover-pack': typeof PrintCutoverPackRoute
  '/settings/gst': typeof SettingsGstRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dev/docs/$slug': typeof DevDocsSlugRoute
  '/print/challan/$id': typeof PrintChallanIdRoute
  '/print/cn/$id': typeof PrintCnIdRoute
  '/print/coc/$id': typeof PrintCocIdRoute
  '/print/dc/$id': typeof PrintDcIdRoute
  '/print/dn/$id': typeof PrintDnIdRoute
  '/print/eway/$id': typeof PrintEwayIdRoute
  '/print/grn/$id': typeof PrintGrnIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/knockout/$id': typeof PrintKnockoutIdRoute
  '/print/opening-jw/$id': typeof PrintOpeningJwIdRoute
  '/print/packing/$id': typeof PrintPackingIdRoute
  '/print/po/$id': typeof PrintPoIdRoute
  '/print/pour/$id': typeof PrintPourIdRoute
  '/print/qr/$lotId': typeof PrintQrLotIdRoute
  '/print/quote/$id': typeof PrintQuoteIdRoute
  '/print/return/$id': typeof PrintReturnIdRoute
  '/print/shipping-bill/$id': typeof PrintShippingBillIdRoute
  '/dev/docs/': typeof DevDocsIndexRoute
  '/stock/lots/$lotId/genealogy': typeof StockLotsLotIdGenealogyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bills': typeof BillsRoute
  '/books': typeof BooksRoute
  '/cutover': typeof CutoverRoute
  '/dispatch': typeof DispatchRoute
  '/foundry': typeof FoundryRoute
  '/grn': typeof GrnRoute
  '/gst': typeof GstRoute
  '/healthz': typeof HealthzRoute
  '/import': typeof ImportRoute
  '/journeys': typeof JourneysRoute
  '/jw': typeof JwRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/masters': typeof MastersRoute
  '/moves': typeof MovesRoute
  '/ncr': typeof NcrRoute
  '/planning': typeof PlanningRoute
  '/po': typeof PoRoute
  '/prod-log': typeof ProdLogRoute
  '/qc': typeof QcRoute
  '/qr-labels': typeof QrLabelsRoute
  '/quotes': typeof QuotesRoute
  '/registers': typeof RegistersRoute
  '/shop': typeof ShopRoute
  '/so': typeof SoRoute
  '/stn': typeof StnRoute
  '/stock': typeof StockRouteWithChildren
  '/subcontract': typeof SubcontractRoute
  '/wo': typeof WoRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/dev/journeys': typeof DevJourneysRoute
  '/genealogy/$lotId': typeof GenealogyLotIdRoute
  '/print/cutover-pack': typeof PrintCutoverPackRoute
  '/settings/gst': typeof SettingsGstRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dev/docs/$slug': typeof DevDocsSlugRoute
  '/print/challan/$id': typeof PrintChallanIdRoute
  '/print/cn/$id': typeof PrintCnIdRoute
  '/print/coc/$id': typeof PrintCocIdRoute
  '/print/dc/$id': typeof PrintDcIdRoute
  '/print/dn/$id': typeof PrintDnIdRoute
  '/print/eway/$id': typeof PrintEwayIdRoute
  '/print/grn/$id': typeof PrintGrnIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/knockout/$id': typeof PrintKnockoutIdRoute
  '/print/opening-jw/$id': typeof PrintOpeningJwIdRoute
  '/print/packing/$id': typeof PrintPackingIdRoute
  '/print/po/$id': typeof PrintPoIdRoute
  '/print/pour/$id': typeof PrintPourIdRoute
  '/print/qr/$lotId': typeof PrintQrLotIdRoute
  '/print/quote/$id': typeof PrintQuoteIdRoute
  '/print/return/$id': typeof PrintReturnIdRoute
  '/print/shipping-bill/$id': typeof PrintShippingBillIdRoute
  '/dev/docs': typeof DevDocsIndexRoute
  '/stock/lots/$lotId/genealogy': typeof StockLotsLotIdGenealogyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bills': typeof BillsRoute
  '/books': typeof BooksRoute
  '/cutover': typeof CutoverRoute
  '/dispatch': typeof DispatchRoute
  '/foundry': typeof FoundryRoute
  '/grn': typeof GrnRoute
  '/gst': typeof GstRoute
  '/healthz': typeof HealthzRoute
  '/import': typeof ImportRoute
  '/journeys': typeof JourneysRoute
  '/jw': typeof JwRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/masters': typeof MastersRoute
  '/moves': typeof MovesRoute
  '/ncr': typeof NcrRoute
  '/planning': typeof PlanningRoute
  '/po': typeof PoRoute
  '/prod-log': typeof ProdLogRoute
  '/qc': typeof QcRoute
  '/qr-labels': typeof QrLabelsRoute
  '/quotes': typeof QuotesRoute
  '/registers': typeof RegistersRoute
  '/shop': typeof ShopRoute
  '/so': typeof SoRoute
  '/stn': typeof StnRoute
  '/stock': typeof StockRouteWithChildren
  '/subcontract': typeof SubcontractRoute
  '/wo': typeof WoRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/dev/docs': typeof DevDocsRouteWithChildren
  '/dev/journeys': typeof DevJourneysRoute
  '/genealogy/$lotId': typeof GenealogyLotIdRoute
  '/print/cutover-pack': typeof PrintCutoverPackRoute
  '/settings/gst': typeof SettingsGstRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dev/docs/$slug': typeof DevDocsSlugRoute
  '/print/challan/$id': typeof PrintChallanIdRoute
  '/print/cn/$id': typeof PrintCnIdRoute
  '/print/coc/$id': typeof PrintCocIdRoute
  '/print/dc/$id': typeof PrintDcIdRoute
  '/print/dn/$id': typeof PrintDnIdRoute
  '/print/eway/$id': typeof PrintEwayIdRoute
  '/print/grn/$id': typeof PrintGrnIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/knockout/$id': typeof PrintKnockoutIdRoute
  '/print/opening-jw/$id': typeof PrintOpeningJwIdRoute
  '/print/packing/$id': typeof PrintPackingIdRoute
  '/print/po/$id': typeof PrintPoIdRoute
  '/print/pour/$id': typeof PrintPourIdRoute
  '/print/qr/$lotId': typeof PrintQrLotIdRoute
  '/print/quote/$id': typeof PrintQuoteIdRoute
  '/print/return/$id': typeof PrintReturnIdRoute
  '/print/shipping-bill/$id': typeof PrintShippingBillIdRoute
  '/dev/docs/': typeof DevDocsIndexRoute
  '/stock/lots/$lotId/genealogy': typeof StockLotsLotIdGenealogyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/bills'
    | '/books'
    | '/cutover'
    | '/dispatch'
    | '/foundry'
    | '/grn'
    | '/gst'
    | '/healthz'
    | '/import'
    | '/journeys'
    | '/jw'
    | '/login'
    | '/maintenance'
    | '/masters'
    | '/moves'
    | '/ncr'
    | '/planning'
    | '/po'
    | '/prod-log'
    | '/qc'
    | '/qr-labels'
    | '/quotes'
    | '/registers'
    | '/shop'
    | '/so'
    | '/stn'
    | '/stock'
    | '/subcontract'
    | '/wo'
    | '/admin/permissions'
    | '/dev/docs'
    | '/dev/journeys'
    | '/genealogy/$lotId'
    | '/print/cutover-pack'
    | '/settings/gst'
    | '/api/auth/$'
    | '/dev/docs/$slug'
    | '/print/challan/$id'
    | '/print/cn/$id'
    | '/print/coc/$id'
    | '/print/dc/$id'
    | '/print/dn/$id'
    | '/print/eway/$id'
    | '/print/grn/$id'
    | '/print/invoice/$id'
    | '/print/knockout/$id'
    | '/print/opening-jw/$id'
    | '/print/packing/$id'
    | '/print/po/$id'
    | '/print/pour/$id'
    | '/print/qr/$lotId'
    | '/print/quote/$id'
    | '/print/return/$id'
    | '/print/shipping-bill/$id'
    | '/dev/docs/'
    | '/stock/lots/$lotId/genealogy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/bills'
    | '/books'
    | '/cutover'
    | '/dispatch'
    | '/foundry'
    | '/grn'
    | '/gst'
    | '/healthz'
    | '/import'
    | '/journeys'
    | '/jw'
    | '/login'
    | '/maintenance'
    | '/masters'
    | '/moves'
    | '/ncr'
    | '/planning'
    | '/po'
    | '/prod-log'
    | '/qc'
    | '/qr-labels'
    | '/quotes'
    | '/registers'
    | '/shop'
    | '/so'
    | '/stn'
    | '/stock'
    | '/subcontract'
    | '/wo'
    | '/admin/permissions'
    | '/dev/journeys'
    | '/genealogy/$lotId'
    | '/print/cutover-pack'
    | '/settings/gst'
    | '/api/auth/$'
    | '/dev/docs/$slug'
    | '/print/challan/$id'
    | '/print/cn/$id'
    | '/print/coc/$id'
    | '/print/dc/$id'
    | '/print/dn/$id'
    | '/print/eway/$id'
    | '/print/grn/$id'
    | '/print/invoice/$id'
    | '/print/knockout/$id'
    | '/print/opening-jw/$id'
    | '/print/packing/$id'
    | '/print/po/$id'
    | '/print/pour/$id'
    | '/print/qr/$lotId'
    | '/print/quote/$id'
    | '/print/return/$id'
    | '/print/shipping-bill/$id'
    | '/dev/docs'
    | '/stock/lots/$lotId/genealogy'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/bills'
    | '/books'
    | '/cutover'
    | '/dispatch'
    | '/foundry'
    | '/grn'
    | '/gst'
    | '/healthz'
    | '/import'
    | '/journeys'
    | '/jw'
    | '/login'
    | '/maintenance'
    | '/masters'
    | '/moves'
    | '/ncr'
    | '/planning'
    | '/po'
    | '/prod-log'
    | '/qc'
    | '/qr-labels'
    | '/quotes'
    | '/registers'
    | '/shop'
    | '/so'
    | '/stn'
    | '/stock'
    | '/subcontract'
    | '/wo'
    | '/admin/permissions'
    | '/dev/docs'
    | '/dev/journeys'
    | '/genealogy/$lotId'
    | '/print/cutover-pack'
    | '/settings/gst'
    | '/api/auth/$'
    | '/dev/docs/$slug'
    | '/print/challan/$id'
    | '/print/cn/$id'
    | '/print/coc/$id'
    | '/print/dc/$id'
    | '/print/dn/$id'
    | '/print/eway/$id'
    | '/print/grn/$id'
    | '/print/invoice/$id'
    | '/print/knockout/$id'
    | '/print/opening-jw/$id'
    | '/print/packing/$id'
    | '/print/po/$id'
    | '/print/pour/$id'
    | '/print/qr/$lotId'
    | '/print/quote/$id'
    | '/print/return/$id'
    | '/print/shipping-bill/$id'
    | '/dev/docs/'
    | '/stock/lots/$lotId/genealogy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BillsRoute: typeof BillsRoute
  BooksRoute: typeof BooksRoute
  CutoverRoute: typeof CutoverRoute
  DispatchRoute: typeof DispatchRoute
  FoundryRoute: typeof FoundryRoute
  GrnRoute: typeof GrnRoute
  GstRoute: typeof GstRoute
  HealthzRoute: typeof HealthzRoute
  ImportRoute: typeof ImportRoute
  JourneysRoute: typeof JourneysRoute
  JwRoute: typeof JwRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MastersRoute: typeof MastersRoute
  MovesRoute: typeof MovesRoute
  NcrRoute: typeof NcrRoute
  PlanningRoute: typeof PlanningRoute
  PoRoute: typeof PoRoute
  ProdLogRoute: typeof ProdLogRoute
  QcRoute: typeof QcRoute
  QrLabelsRoute: typeof QrLabelsRoute
  QuotesRoute: typeof QuotesRoute
  RegistersRoute: typeof RegistersRoute
  ShopRoute: typeof ShopRoute
  SoRoute: typeof SoRoute
  StnRoute: typeof StnRoute
  StockRoute: typeof StockRouteWithChildren
  SubcontractRoute: typeof SubcontractRoute
  WoRoute: typeof WoRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  DevDocsRoute: typeof DevDocsRouteWithChildren
  DevJourneysRoute: typeof DevJourneysRoute
  GenealogyLotIdRoute: typeof GenealogyLotIdRoute
  PrintCutoverPackRoute: typeof PrintCutoverPackRoute
  SettingsGstRoute: typeof SettingsGstRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PrintChallanIdRoute: typeof PrintChallanIdRoute
  PrintCnIdRoute: typeof PrintCnIdRoute
  PrintCocIdRoute: typeof PrintCocIdRoute
  PrintDcIdRoute: typeof PrintDcIdRoute
  PrintDnIdRoute: typeof PrintDnIdRoute
  PrintEwayIdRoute: typeof PrintEwayIdRoute
  PrintGrnIdRoute: typeof PrintGrnIdRoute
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
  PrintKnockoutIdRoute: typeof PrintKnockoutIdRoute
  PrintOpeningJwIdRoute: typeof PrintOpeningJwIdRoute
  PrintPackingIdRoute: typeof PrintPackingIdRoute
  PrintPoIdRoute: typeof PrintPoIdRoute
  PrintPourIdRoute: typeof PrintPourIdRoute
  PrintQrLotIdRoute: typeof PrintQrLotIdRoute
  PrintQuoteIdRoute: typeof PrintQuoteIdRoute
  PrintReturnIdRoute: typeof PrintReturnIdRoute
  PrintShippingBillIdRoute: typeof PrintShippingBillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutover': {
      id: '/cutover'
      path: '/cutover'
      fullPath: '/cutover'
      preLoaderRoute: typeof CutoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundry': {
      id: '/foundry'
      path: '/foundry'
      fullPath: '/foundry'
      preLoaderRoute: typeof FoundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grn': {
      id: '/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof GrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jw': {
      id: '/jw'
      path: '/jw'
      fullPath: '/jw'
      preLoaderRoute: typeof JwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moves': {
      id: '/moves'
      path: '/moves'
      fullPath: '/moves'
      preLoaderRoute: typeof MovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncr': {
      id: '/ncr'
      path: '/ncr'
      fullPath: '/ncr'
      preLoaderRoute: typeof NcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po': {
      id: '/po'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof PoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prod-log': {
      id: '/prod-log'
      path: '/prod-log'
      fullPath: '/prod-log'
      preLoaderRoute: typeof ProdLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-labels': {
      id: '/qr-labels'
      path: '/qr-labels'
      fullPath: '/qr-labels'
      preLoaderRoute: typeof QrLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers': {
      id: '/registers'
      path: '/registers'
      fullPath: '/registers'
      preLoaderRoute: typeof RegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/so': {
      id: '/so'
      path: '/so'
      fullPath: '/so'
      preLoaderRoute: typeof SoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stn': {
      id: '/stn'
      path: '/stn'
      fullPath: '/stn'
      preLoaderRoute: typeof StnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontract': {
      id: '/subcontract'
      path: '/subcontract'
      fullPath: '/subcontract'
      preLoaderRoute: typeof SubcontractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wo': {
      id: '/wo'
      path: '/wo'
      fullPath: '/wo'
      preLoaderRoute: typeof WoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/docs': {
      id: '/dev/docs'
      path: '/dev/docs'
      fullPath: '/dev/docs'
      preLoaderRoute: typeof DevDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/journeys': {
      id: '/dev/journeys'
      path: '/dev/journeys'
      fullPath: '/dev/journeys'
      preLoaderRoute: typeof DevJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genealogy/$lotId': {
      id: '/genealogy/$lotId'
      path: '/genealogy/$lotId'
      fullPath: '/genealogy/$lotId'
      preLoaderRoute: typeof GenealogyLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/cutover-pack': {
      id: '/print/cutover-pack'
      path: '/print/cutover-pack'
      fullPath: '/print/cutover-pack'
      preLoaderRoute: typeof PrintCutoverPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/gst': {
      id: '/settings/gst'
      path: '/settings/gst'
      fullPath: '/settings/gst'
      preLoaderRoute: typeof SettingsGstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/docs/': {
      id: '/dev/docs/'
      path: '/'
      fullPath: '/dev/docs/'
      preLoaderRoute: typeof DevDocsIndexRouteImport
      parentRoute: typeof DevDocsRoute
    }
    '/dev/docs/$slug': {
      id: '/dev/docs/$slug'
      path: '/$slug'
      fullPath: '/dev/docs/$slug'
      preLoaderRoute: typeof DevDocsSlugRouteImport
      parentRoute: typeof DevDocsRoute
    }
    '/print/challan/$id': {
      id: '/print/challan/$id'
      path: '/print/challan/$id'
      fullPath: '/print/challan/$id'
      preLoaderRoute: typeof PrintChallanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/cn/$id': {
      id: '/print/cn/$id'
      path: '/print/cn/$id'
      fullPath: '/print/cn/$id'
      preLoaderRoute: typeof PrintCnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/coc/$id': {
      id: '/print/coc/$id'
      path: '/print/coc/$id'
      fullPath: '/print/coc/$id'
      preLoaderRoute: typeof PrintCocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/dc/$id': {
      id: '/print/dc/$id'
      path: '/print/dc/$id'
      fullPath: '/print/dc/$id'
      preLoaderRoute: typeof PrintDcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/dn/$id': {
      id: '/print/dn/$id'
      path: '/print/dn/$id'
      fullPath: '/print/dn/$id'
      preLoaderRoute: typeof PrintDnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/eway/$id': {
      id: '/print/eway/$id'
      path: '/print/eway/$id'
      fullPath: '/print/eway/$id'
      preLoaderRoute: typeof PrintEwayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/grn/$id': {
      id: '/print/grn/$id'
      path: '/print/grn/$id'
      fullPath: '/print/grn/$id'
      preLoaderRoute: typeof PrintGrnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/invoice/$id': {
      id: '/print/invoice/$id'
      path: '/print/invoice/$id'
      fullPath: '/print/invoice/$id'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/knockout/$id': {
      id: '/print/knockout/$id'
      path: '/print/knockout/$id'
      fullPath: '/print/knockout/$id'
      preLoaderRoute: typeof PrintKnockoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/opening-jw/$id': {
      id: '/print/opening-jw/$id'
      path: '/print/opening-jw/$id'
      fullPath: '/print/opening-jw/$id'
      preLoaderRoute: typeof PrintOpeningJwIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/packing/$id': {
      id: '/print/packing/$id'
      path: '/print/packing/$id'
      fullPath: '/print/packing/$id'
      preLoaderRoute: typeof PrintPackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/po/$id': {
      id: '/print/po/$id'
      path: '/print/po/$id'
      fullPath: '/print/po/$id'
      preLoaderRoute: typeof PrintPoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/pour/$id': {
      id: '/print/pour/$id'
      path: '/print/pour/$id'
      fullPath: '/print/pour/$id'
      preLoaderRoute: typeof PrintPourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/qr/$lotId': {
      id: '/print/qr/$lotId'
      path: '/print/qr/$lotId'
      fullPath: '/print/qr/$lotId'
      preLoaderRoute: typeof PrintQrLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/quote/$id': {
      id: '/print/quote/$id'
      path: '/print/quote/$id'
      fullPath: '/print/quote/$id'
      preLoaderRoute: typeof PrintQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/return/$id': {
      id: '/print/return/$id'
      path: '/print/return/$id'
      fullPath: '/print/return/$id'
      preLoaderRoute: typeof PrintReturnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/shipping-bill/$id': {
      id: '/print/shipping-bill/$id'
      path: '/print/shipping-bill/$id'
      fullPath: '/print/shipping-bill/$id'
      preLoaderRoute: typeof PrintShippingBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/lots/$lotId/genealogy': {
      id: '/stock/lots/$lotId/genealogy'
      path: '/lots/$lotId/genealogy'
      fullPath: '/stock/lots/$lotId/genealogy'
      preLoaderRoute: typeof StockLotsLotIdGenealogyRouteImport
      parentRoute: typeof StockRoute
    }
  }
}

interface StockRouteChildren {
  StockLotsLotIdGenealogyRoute: typeof StockLotsLotIdGenealogyRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockLotsLotIdGenealogyRoute: StockLotsLotIdGenealogyRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

interface DevDocsRouteChildren {
  DevDocsSlugRoute: typeof DevDocsSlugRoute
  DevDocsIndexRoute: typeof DevDocsIndexRoute
}

const DevDocsRouteChildren: DevDocsRouteChildren = {
  DevDocsSlugRoute: DevDocsSlugRoute,
  DevDocsIndexRoute: DevDocsIndexRoute,
}

const DevDocsRouteWithChildren =
  DevDocsRoute._addFileChildren(DevDocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BillsRoute: BillsRoute,
  BooksRoute: BooksRoute,
  CutoverRoute: CutoverRoute,
  DispatchRoute: DispatchRoute,
  FoundryRoute: FoundryRoute,
  GrnRoute: GrnRoute,
  GstRoute: GstRoute,
  HealthzRoute: HealthzRoute,
  ImportRoute: ImportRoute,
  JourneysRoute: JourneysRoute,
  JwRoute: JwRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  MastersRoute: MastersRoute,
  MovesRoute: MovesRoute,
  NcrRoute: NcrRoute,
  PlanningRoute: PlanningRoute,
  PoRoute: PoRoute,
  ProdLogRoute: ProdLogRoute,
  QcRoute: QcRoute,
  QrLabelsRoute: QrLabelsRoute,
  QuotesRoute: QuotesRoute,
  RegistersRoute: RegistersRoute,
  ShopRoute: ShopRoute,
  SoRoute: SoRoute,
  StnRoute: StnRoute,
  StockRoute: StockRouteWithChildren,
  SubcontractRoute: SubcontractRoute,
  WoRoute: WoRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  DevDocsRoute: DevDocsRouteWithChildren,
  DevJourneysRoute: DevJourneysRoute,
  GenealogyLotIdRoute: GenealogyLotIdRoute,
  PrintCutoverPackRoute: PrintCutoverPackRoute,
  SettingsGstRoute: SettingsGstRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PrintChallanIdRoute: PrintChallanIdRoute,
  PrintCnIdRoute: PrintCnIdRoute,
  PrintCocIdRoute: PrintCocIdRoute,
  PrintDcIdRoute: PrintDcIdRoute,
  PrintDnIdRoute: PrintDnIdRoute,
  PrintEwayIdRoute: PrintEwayIdRoute,
  PrintGrnIdRoute: PrintGrnIdRoute,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
  PrintKnockoutIdRoute: PrintKnockoutIdRoute,
  PrintOpeningJwIdRoute: PrintOpeningJwIdRoute,
  PrintPackingIdRoute: PrintPackingIdRoute,
  PrintPoIdRoute: PrintPoIdRoute,
  PrintPourIdRoute: PrintPourIdRoute,
  PrintQrLotIdRoute: PrintQrLotIdRoute,
  PrintQuoteIdRoute: PrintQuoteIdRoute,
  PrintReturnIdRoute: PrintReturnIdRoute,
  PrintShippingBillIdRoute: PrintShippingBillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
